State.delete_all
State.create(name: 'Alabama', initials:'AL')
State.create(name: 'Alaska', initials:'AK')
State.create(name: 'Arizona', initials:'AZ')
State.create(name: 'Arkansas', initials:'AR')
State.create(name: 'California', initials:'CA')
State.create(name: 'Colorado', initials:'CO')
State.create(name: 'Connecticut', initials:'CT')
State.create(name: 'Delaware', initials:'DE')
State.create(name: 'Florida', initials:'FL')
State.create(name: 'Georgia', initials:'GA')
State.create(name: 'Hawaii', initials:'HI')
State.create(name: 'Idaho', initials:'ID')
State.create(name: 'Illinois', initials:'IL')
State.create(name: 'Indiana', initials:'IN')
State.create(name: 'Iowa', initials:'IA')
State.create(name: 'Kansas', initials:'KS')
State.create(name: 'Kentucky', initials:'KY')
State.create(name: 'Louisiana', initials:'LA')
State.create(name: 'Maine', initials:'ME')
State.create(name: 'Maryland', initials:'MD')
State.create(name: 'Massachusetts', initials:'MA')
State.create(name: 'Michigan', initials:'MI')
State.create(name: 'Minnesota', initials:'MN')
State.create(name: 'Mississippi', initials:'MS')
State.create(name: 'Missouri', initials:'MO')
State.create(name: 'Montana', initials:'MT')
State.create(name: 'Nebraska', initials:'NE')
State.create(name: 'Nevada', initials:'NV')
State.create(name: 'New Hampshire', initials:'NH')
State.create(name: 'New Jersey', initials:'NJ')
State.create(name: 'New Mexico', initials:'NM')
State.create(name: 'New York', initials:'NY')
State.create(name: 'North Carolina', initials:'NC')
State.create(name: 'North Dakota', initials:'ND')
State.create(name: 'Ohio', initials:'OH')
State.create(name: 'Oklahoma', initials:'OK')
State.create(name: 'Oregon', initials:'OR')
State.create(name: 'Pennsylvania', initials:'PA')
State.create(name: 'Rhode Island', initials:'RI')
State.create(name: 'South Carolina', initials:'SC')
State.create(name: 'South Dakota', initials:'SD')
State.create(name: 'Tennessee', initials:'TN')
State.create(name: 'Texas', initials:'TX')
State.create(name: 'Utah', initials:'UT')
State.create(name: 'Vermont', initials:'VT')
State.create(name: 'Virginia', initials:'VA')
State.create(name: 'Washington', initials:'WA')
State.create(name: 'West Virginia', initials:'WV')
State.create(name: 'Wisconsin', initials:'WI')
State.create(name: 'Wyoming', initials:'WY')

